apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-date
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: "pv-date-app"